### ISSUE TITLE
GPIO8 on ESP32-C6

### ISSUE THREAD

**Issue by eco3xfr** [xmow49/ESP32H2-Zigbee-Demo#5]
Hello, on the ESP32-C6, the DHT22 program works well on the GPIO8 but it is also the integrated RGB LED, I tried to change the GPIO but without success.

**Comment by xmow49** [comment]
Slt,
As tu essayé de changer le gpio ici ?
https://github.com/xmow49/ESP32H2-Zigbee-Demo/blob/3c7142e868d0a40b8ad932537786f2872bce058c/main/esp_zb_light.c#L49

**Comment by eco3xfr** [comment]
Bjr, oui c'est là que j'ai essayé de changer, 
et aussi ici :
https://github.com/xmow49/ESP32H2-Zigbee-Demo/blob/3c7142e868d0a40b8ad932537786f2872bce058c/main/DHT22.c#L35C1-L35C43
mais sans résultat, ça ne fonctionne qu'avec la PIN 8, mais la LED RGB s'allume, avec les autres pin j'obtiens "DHT timeout..."

**Comment by eco3xfr** [comment]
Peut être un problème de pull up ou config de pin mais je ne sais pas comment faire avec ESP-IDE,
avec ArduinoIDE toutes les pin fonctionnent avec le DHT22 (mais pas le Zigbee)

**Comment by xmow49** [comment]
C'est quel pin que tu essais de mettre ? je peux regarder ca de mon coté.

**Comment by eco3xfr** [comment]
les pin 10 et 11 sont libres, les autres ont plusieurs fonctions mais marches aussi avec ArduinoIDE

**Comment by eco3xfr** [comment]
c'est un nanoESP32-C6
https://github.com/wuxx/nanoESP32-C6/blob/master/README_en.md

**Comment by eco3xfr** [comment]
Je viens de faire un essais avec un ESP32-H2 devkit,
j'ai modifié :
 `void dht22_task(void *pvParameters)
{
    while (1)
    {
        setDHTgpio(10);
        int ret = readDHT();`

ça fonctionne bien sur le PIN 10.
je ne comprends pas pourquoi pas avec le C6 ?

**Comment by eco3xfr** [comment]
Comme je n’aime pas rester sur un échec, j’ai refais des tests de mes C6 et H2 avec un nouveau DHT22 commandé sur ALI, et ça fonctionne bien sur la PIN 10, donc j’en déduit que mes anciens capteurs posent problème.
le nouveau est sur CI avec résistance R1 et C1.
il y a certainement des options pull up ou autre qui ne fonctionne que sur la PIN 8 avec les anciens DHT sans résistance.
![20240319_205838](https://github.com/xmow49/ESP32H2-Zigbee-Demo/assets/148893739/df6f282a-a2f5-4bf5-b6bf-74e7be39f3ee)
