### ISSUE TITLE
Can't build due to partitions.csv

### ISSUE THREAD

**Issue by Layochi** [xmow49/ESP32H2-Zigbee-Demo#6]
When you try to build the project, you obtain :

`Partition factory invalid: Size 0xa2800 is not aligned to 0x1000` 

Because of an error in partitions.csv

**Comment by xmow49** [comment]
Slt,
Merci pour ta PR, j'ai merge.
Tu utilise quel version de IDF ? Ils ont du changer des choses je pense.

**Comment by Layochi** [comment]
Salut, j'utilise la version 1.7.1.

Est-ce que se serait possible de discuter en mp, j'ai quelques questions sur ton exemple ?
