### ISSUE TITLE
Issue while building

### ISSUE THREAD

**Issue by bastoonch** [xmow49/ESP32H2-Zigbee-Demo#9]
Hi,

I am having the following issue while building for esp32h2.

_Python 3.11.1
espressif/esp-zboss-lib (1.3.2)
espressif/esp-zigbee-lib (1.3.2)
espressif/led_strip (2.0.0)
idf (5.1.3)_

In file included from /Users/Seb/esp/ESP32H2-Zigbee-Demo/main/esp_zb_light.c:7:
/Users/Seb/esp/ESP32H2-Zigbee-Demo/main/esp_zb_light.c: In function 'app_main':
/Users/Seb/esp/ESP32H2-Zigbee-Demo/main/esp_zb_light.h:22:23: error: 'RADIO_MODE_NATIVE' undeclared (first use in this function); did you mean 'ZB_RADIO_MODE_NATIVE'?
   22 |         .radio_mode = RADIO_MODE_NATIVE, \
      |                       ^~~~~~~~~~~~~~~~~
/Users/Seb/esp/ESP32H2-Zigbee-Demo/main/esp_zb_light.c:262:25: note: in expansion of macro 'ESP_ZB_DEFAULT_RADIO_CONFIG'
  262 |         .radio_config = ESP_ZB_DEFAULT_RADIO_CONFIG(),
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Seb/esp/ESP32H2-Zigbee-Demo/main/esp_zb_light.h:22:23: note: each undeclared identifier is reported only once for each function it appears in
   22 |         .radio_mode = RADIO_MODE_NATIVE, \
      |                       ^~~~~~~~~~~~~~~~~
/Users/Seb/esp/ESP32H2-Zigbee-Demo/main/esp_zb_light.c:262:25: note: in expansion of macro 'ESP_ZB_DEFAULT_RADIO_CONFIG'
  262 |         .radio_config = ESP_ZB_DEFAULT_RADIO_CONFIG(),
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Seb/esp/ESP32H2-Zigbee-Demo/main/esp_zb_light.h:27:33: error: 'HOST_CONNECTION_MODE_NONE' undeclared (first use in this function); did you mean 'ZB_HOST_CONNECTION_MODE_NONE'?
   27 |         .host_connection_mode = HOST_CONNECTION_MODE_NONE, \
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Seb/esp/ESP32H2-Zigbee-Demo/main/esp_zb_light.c:263:24: note: in expansion of macro 'ESP_ZB_DEFAULT_HOST_CONFIG'
  263 |         .host_config = ESP_ZB_DEFAULT_HOST_CONFIG(),

Do you have any clue ?

**Comment by xmow49** [comment]
Hi,
This PR fix the problem https://github.com/xmow49/ESP32H2-Zigbee-Demo/pull/10
You can retry
